### ISSUE TITLE
[Q] Dynamosm?

### ISSUE THREAD

**Issue by nrenner** [OSMCha/osm-adiff-service#14]
The [initial README.md](https://github.com/OSMCha/osm-adiff-service/blob/96d05d7b6acbb304f9fe69453c89b1c0ff009258/README.md?plain=1#L131) mentioned "Dynamosm":

> ### This sounds like quite a lot of duct-tape
> 
> It is. For now, this is going to improve our workflows, but while this in place we can continue working on Dynamosm.

I haven't found any information about that except [this](https://github.com/mapbox/osm-compare/blob/e78d884abc39e2765d49d1457aee38071181b388/docs/new-compare-function.md?plain=1#L92-L93):
> Query api-dynamosm: https://jzvqzn73ca.execute-api.us-east-1.amazonaws.com/api/feature/way/430124248?version=4 Get both the old and new version json.

Which looks like something we might rather want instead of querying the Overpass API by timestamps and bbox ([osmcha-frontend#652](https://github.com/OSMCha/osmcha-frontend/issues/652)).

So I wonder what Dynamosm is/was and why it hasn't worked out as a replacement of the current setup?

**Comment by batpad** [comment]
We should definitely update the README :-)

Dynamosm was afaik, an internal Mapbox tool that used AWS' DynamoDB to maintain a node cache and create full geometries based on planet replication. I don't believe that it is either used or maintained any more.

Sorry about the confusion - @willemarcel @jake-low we should probably remove the reference from the README.

**Comment by nrenner** [comment]
@batpad thanks for the answer!

That Dynamosm reference is already removed from the current readme, I linked to an old version.

It didn't confuse me, but caught my attention, because I'm interested in potential alternatives to the Overpass API (see [osmcha-frontend#652](https://github.com/OSMCha/osmcha-frontend/issues/652)).

One idea might be a key-value store like DynamoDB to lookup changesets and referenced object versions by id (type+id+version). So it's also interesting to hear what didn't work out (and why).
